# Generated by Django 5.2.4 on 2026-09-13 22:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (e.g. 0241234567 or +233241234567).', regex='^\\+?[0-9\\s-]{9,15}$')]),
        ),
    ]
